services:
  app:
    container_name: file_upload_system
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./file_upload_system/.env
    volumes:
      - static-data:/app/staticfiles
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py collectstatic --noinput &&
            python3 manage.py runserver 0.0.0.0:8000"

volumes:
  static-data:
