# Generated by Django 5.0 on 2024-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaccesslog',
            name='access_type',
            field=models.CharField(max_length=10),
        ),
    ]
