name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AWS_INSTANCE_SSH_KEY }}

      - name: Test and Deploy on EC2
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            set -e  # Exit immediately if a command exits with a non-zero status
            cd /home/${{ secrets.SERVER_USER }}/file-upload-system

            git pull https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/emrahbatigun/file-upload-system.git main

            echo "Building Docker containers for testing..."
            docker-compose -f docker-compose.yml build

            echo "Running tests..."
            docker-compose -f docker-compose.yml exec app pytest
            TEST_EXIT_CODE=$?

            if [ $TEST_EXIT_CODE -eq 0 ]; then
              echo "Tests passed. Deploying to production..."
              docker-compose up -d
            else
              echo "Tests failed. Deployment aborted."
              exit 1
            fi

            docker image prune -f
          EOF
